import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.recipes': 'Recipes',
    'nav.location': 'Find us',
    'nav.contact': 'Contact',
    'nav.games': 'Games',
    
    // Homepage
    'home.hero.slogan': 'A Contented Mind Is a Perpetual Feast',
    'home.hero.exploreRecipes': 'Cook with us',
    'home.hero.visitStore': 'Find us',
    'home.gallery.title': 'Come in.',
    'home.gallery.description': 'Aisles of Far East staples in Earley, Reading - fresh, authentic, and ready for your next cook.',
    'home.gallery.cta': 'Get directions',
    'home.ticker.noodles': 'Noodles',
    'home.ticker.sauces': 'Sauces',
    'home.ticker.rice': 'Rice & grains',
    'home.ticker.snacks': 'Snacks',
    'home.ticker.frozen': 'Frozen',
    'home.ticker.drinks': 'Drinks',
    'home.ticker.spices': 'Spices',
    'home.ticker.tea': 'Tea',
    'home.featuredRecipes.title': 'Cook with us.',
    'home.featuredRecipes.stem': 'Cook with',
    'home.featuredRecipes.description': 'Recipes built for what you can pick up on our shelves.',
    'home.featuredRecipes.viewAll': 'See all recipes',
    'home.featuredRecipes.loading': 'Loading recipes...',
    'home.featuredRecipes.emptyTitle': 'Recipes on the way.',
    'home.featuredRecipes.emptyDesc': 'We\'re plating up dishes you can cook with ingredients from Cmart.',
    'home.exploreMore.title': 'Keep going.',
    'home.exploreMore.description': 'Story, store, hello, or a quick game - pick a path.',
    'home.exploreMore.about': 'Our story.',
    'home.exploreMore.aboutDesc': 'Reading since 2013. Quality, community, and feeling at home.',
    'home.exploreMore.recipes': 'Recipes',
    'home.exploreMore.recipesDesc': 'Discover authentic Asian recipes and cooking inspiration',
    'home.exploreMore.findUs': 'Find us.',
    'home.exploreMore.findUsDesc': 'ASDA Mall, Lower Earley. Easy by bus or car.',
    'home.exploreMore.contact': 'Say hello.',
    'home.exploreMore.contactDesc': 'Questions about the store, products, or a visit.',
    'home.exploreMore.learnMore': 'Read more',
    'home.exploreMore.viewRecipes': 'View Recipes',
    'home.exploreMore.getDirections': 'Open maps',
    'home.exploreMore.sendMessage': 'Write to us',
    'home.exploreMore.games': 'Play.',
    'home.exploreMore.gamesDesc': 'Build a recipe against the clock in our kitchen game.',
    'home.exploreMore.playNow': 'Start playing',
    
    // Footer
    'footer.description': 'Your trusted source for authentic oriental groceries in Earley, Reading. Quality products, exceptional service.',
    'footer.quickLinks': 'Quick Links',
    'footer.storeInfo': 'Store Information',
    'footer.openingHours': 'Opening Hours',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    
    // Recipes
    'recipes.hero.badge': 'Recipes',
    'recipes.hero.title': 'Cook with us.',
    'recipes.hero.stem': 'Cook with',
    'recipes.hero.description': 'Authentic Asian recipes using ingredients from our shelves.',
    'recipes.cycle.1': 'what\'s on the shelf.',
    'recipes.cycle.2': 'dumpling nights.',
    'recipes.cycle.3': 'leftover rice.',
    'recipes.cycle.4': 'a crowded table.',
    'recipes.cycle.5': 'Earley evenings.',
    'recipes.filters.search': 'Search recipes...',
    'recipes.filters.cuisine': 'Cuisine',
    'recipes.filters.difficulty': 'Difficulty',
    'recipes.filters.allergies': 'Exclude allergies',
    'recipes.filters.clear': 'Clear',
    'recipes.filters.clearAll': 'Clear filters',
    'recipes.results.found': 'recipe',
    'recipes.results.foundPlural': 'recipes',
    'recipes.empty.title': 'Nothing here yet.',
    'recipes.empty.description': 'Try a different cuisine, difficulty, or search term.',
    'recipes.card.viewRecipe': 'View recipe',
    'recipes.categories.all': 'All',
    'recipes.categories.chinese': 'Chinese',
    'recipes.categories.japanese': 'Japanese',
    'recipes.categories.korean': 'Korean',
    'recipes.categories.thai': 'Thai',
    'recipes.categories.vietnamese': 'Vietnamese',
    'recipes.categories.indian': 'Indian',
    'recipes.difficulty.all': 'All',
    'recipes.difficulty.easy': 'Easy',
    'recipes.difficulty.medium': 'Medium',
    'recipes.difficulty.hard': 'Hard',
    'recipes.filters.title': 'Filters',
    'recipes.filters.searchLabel': 'Search',
    'recipes.allergies.gluten': 'Gluten',
    'recipes.allergies.dairy': 'Dairy',
    'recipes.allergies.nuts': 'Nuts',
    'recipes.allergies.shellfish': 'Shellfish',
    'recipes.allergies.eggs': 'Eggs',
    'recipes.allergies.soy': 'Soy',
    'recipes.allergies.fish': 'Fish',
    
    // Location
    'location.hero.title': 'Find us.',
    'location.hero.description': 'ASDA Mall, Lower Earley - easy by bus or car, with free parking on site.',
    'location.address.title': 'Address',
    'location.hours.title': 'Opening hours',
    'location.hours.description': 'We\'re open throughout the week for your convenience',
    'location.bus.title': 'By bus',
    'location.bus.routes': 'Bus Routes',
    'location.bus.walking': 'Walking Distance',
    'location.bus.stop': 'Bus stop is located near the ASDA Mall entrance',
    'location.car.title': 'By car',
    'location.car.parking': 'Parking',
    'location.car.location': 'Location',
    'location.car.access': 'Easy access from major roads',
    
    // Contact
    'contact.hero.title': 'Say hello.',
    'contact.hero.description': 'Questions about the store, products, or a visit. Drop us a line.',
    'contact.form.title': 'Send Us a Message',
    'contact.form.description': 'We typically respond within 24 hours',
    'contact.card.visit': 'Visit Us',
    'contact.card.visitDesc': 'Come see us in store',
    'contact.card.hours': 'Store Hours',
    'contact.card.response': 'Quick Response',
    'contact.card.responseDesc': 'We\'ll get back to you soon',
    'contact.email': 'cmart@fortunefoods.co.uk',    
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.section1.title': 'Introduction',
    'privacy.section1.content': 'Cmart Oriental Ltd. ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website.',
    'privacy.section2.title': 'Information We Collect',
    'privacy.section2.content': 'We may collect information about you in a variety of ways. The information we may collect includes:',
    'privacy.section2.item1': 'Personal data such as your name and email address when you contact us',
    'privacy.section2.item2': 'Usage data such as your IP address, browser type, and pages visited',
    'privacy.section2.item3': 'Cookies and tracking technologies to enhance your experience',
    'privacy.section2.item4': 'Any other information you voluntarily provide to us',
    'privacy.section3.title': 'How We Use Your Information',
    'privacy.section3.content': 'We use the information we collect to respond to your inquiries, improve our website, and provide you with relevant information about our products and services.',
    'privacy.section4.title': 'Data Security',
    'privacy.section4.content': 'We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the Internet is 100% secure.',
    'privacy.section5.title': 'Third-Party Services',
    'privacy.section5.content': 'Our website may contain links to third-party websites. We are not responsible for the privacy practices of these external sites.',
    'privacy.section6.title': 'Contact Us',
    'privacy.section6.content': 'If you have any questions about this Privacy Policy, please contact us through our contact form.',
    'privacy.contact': 'For inquiries, please visit our Contact page.',
    
    // Terms of Use
    'terms.title': 'Terms of Use',
    'terms.lastUpdated': 'Last Updated',
    'terms.section1.title': 'Acceptance of Terms',
    'terms.section1.content': 'By accessing and using this website, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use this website.',
    'terms.section2.title': 'Use License',
    'terms.section2.content': 'Permission is granted to temporarily download one copy of the materials on Cmart\'s website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.',
    'terms.section3.title': 'Disclaimer',
    'terms.section3.content': 'The materials on Cmart\'s website are provided on an "as is" basis. Cmart makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties.',
    'terms.section4.title': 'Limitations',
    'terms.section4.content': 'In no event shall Cmart or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on Cmart\'s website.',
    'terms.section5.title': 'Accuracy of Materials',
    'terms.section5.content': 'The materials appearing on Cmart\'s website could include technical, typographical, or photographic errors. Cmart does not warrant that any of the materials on its website are accurate, complete, or current.',
    'terms.section6.title': 'Links',
    'terms.section6.content': 'Cmart has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Cmart.',
    'terms.section7.title': 'Modifications',
    'terms.section7.content': 'Cmart may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.',
    'terms.section8.title': 'Recipe Disclaimer',
    'terms.section8.content': 'The recipes provided on this website are for informational and entertainment purposes only. Cmart Oriental Ltd. makes no representations or warranties regarding the accuracy, completeness, or suitability of any recipe for any particular purpose. You acknowledge that cooking involves inherent risks, including but not limited to food allergies, foodborne illness, and kitchen accidents. By using any recipe from this website, you agree that Cmart Oriental Ltd. and its affiliates, employees, and agents shall not be liable for any injuries, damages, losses, or health issues arising from the preparation, consumption, or use of any recipe. You are solely responsible for ensuring that ingredients are safe for consumption, that you follow proper food safety practices, and that you are aware of any allergies or dietary restrictions. Always consult with a qualified healthcare professional or nutritionist if you have concerns about food allergies, dietary requirements, or health conditions.',
    'terms.contact': 'For questions about these Terms of Use, please contact us through our Contact page.',
    
    // About
    'about.hero.title': 'Our story.',
    'about.hero.badge': 'Our Story',
    'about.hero.description': 'Reading since 2013. A neighbourhood Asian grocer built on quality, community, and feeling at home.',
    'about.eyebrow': 'Since 2013',
    'about.quote.label': 'Why we opened',
    'about.quote.line1': 'More than a store.',
    'about.quote.line2': 'A place to gather over Asian food and feel welcome.',
    'about.quote.support': 'That idea still shapes every shelf we stock and every person we greet.',
    'about.section.roots': 'From Reading outwards.',
    'about.section.home': 'Aisles with belonging.',
    'about.content.paragraph1': 'Cmart began in the heart of Reading in 2013 with a simple idea: more than a store, a place where people gather over Asian food and feel welcome. From those modest beginnings we\'ve grown with the support of our customers and the dedication of our team.',
    'about.content.paragraph2': 'As we expand beyond Reading, quality and community stay at the centre. Every product is carefully chosen. We source directly from suppliers across the Far East, so what you find on our shelves stays authentic and fresh.',
    'about.content.paragraph3': 'Our aisles hold groceries, and also stories and a sense of belonging. Whether you\'re a regular or visiting for the first time, you\'re part of the Cmart family.',
    'about.content.paragraph4': 'We keep the same founding promise: top-quality products, a warm welcome, and care for the people who shop with us.',
    'about.content.thanks': 'Thank you for being part of the journey.',
    'about.storeInfo.title': 'Store Information',
    'about.storeInfo.address': 'Address',
    'about.storeInfo.hours': 'Opening Hours',
    'about.storeInfo.parking': 'Parking',
    'about.storeInfo.parkingDesc': 'Convenient parking available nearby',
    'about.cta.findUs': 'Find us',
    'about.cta.sayHello': 'Say hello',
    'about.cta.cook': 'Cook with us',
    
    // Games
    'games.back': 'Back to Home',
    'games.score': 'Score',
    'games.time': 'Time',
    'games.streak': 'Streak',
    'games.highScore': 'High Score',
    'games.start': 'Start Game',
    'games.playAgain': 'Play Again',
    'games.gameOver': 'Game Over!',
    'games.points': 'Points',
    'games.correct': 'Correct',
    'games.wrong': 'Wrong',
    'games.newHighScore': 'New High Score!',
    'games.recipeBuilder.title': 'Recipe Builder Challenge',
    'games.recipeBuilder.description': 'Match ingredients to recipes and score points!',
    'games.recipeBuilder.instructions': 'How to Play',
    'games.recipeBuilder.rule1': 'Select the correct ingredients for each recipe',
    'games.recipeBuilder.rule2': 'Get +10 points for each correct ingredient',
    'games.recipeBuilder.rule3': 'Get +20 bonus for every 3 correct in a row (streak)',
    'games.recipeBuilder.rule4': 'Get +50 bonus for completing a recipe perfectly',
    'games.recipeBuilder.selectIngredients': 'Select the correct ingredients:',
    'games.recipeBuilder.availableIngredients': 'Available Ingredients',
    
    // Location - additional keys
    'location.hero.badge': 'Directions',
    'location.map.title': 'Map',
    'location.map.openMaps': 'Open in Google Maps',
    'location.address.description': 'Inside the ASDA Mall for easy shopping and parking.',
    'location.transport.title': 'Getting here.',
    'location.transport.description': 'Bus or car - both drop you a short walk from the door.',
    'location.bus.routesLabel': 'Routes',
    'location.bus.stopDesc': 'Get off at Lower Earley stop',
    'location.bus.walkingLabel': 'Walk',
    'location.bus.walkingTime': '2-3 minutes',
    'location.car.parkingLabel': 'Parking',
    'location.car.parkingDesc': 'Free parking for customers in the ASDA car park.',
    'location.car.locationLabel': 'Location',
    'location.car.locationDesc': 'Store is within the ASDA Mall',
    'location.days.monThu': 'Monday - Thursday',
    'location.days.friday': 'Friday',
    'location.days.saturday': 'Saturday',
    'location.days.sunday': 'Sunday',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.recipes': '食谱',
    'nav.location': '找到我们',
    'nav.contact': '联系我们',
    'nav.games': '游戏',
    
    // Homepage
    'home.hero.slogan': '知足常乐',
    'home.hero.exploreRecipes': '一起下厨',
    'home.hero.visitStore': '找到我们',
    'home.gallery.title': '进来看看。',
    'home.gallery.description': 'Earley, Reading 的远东食材货架，新鲜正宗，随时开启下一次下厨。',
    'home.gallery.cta': '查看路线',
    'home.ticker.noodles': '面条',
    'home.ticker.sauces': '酱料',
    'home.ticker.rice': '米与杂粮',
    'home.ticker.snacks': '零食',
    'home.ticker.frozen': '冷冻',
    'home.ticker.drinks': '饮品',
    'home.ticker.spices': '香料',
    'home.ticker.tea': '茶',
    'home.featuredRecipes.title': '和我们一起下厨。',
    'home.featuredRecipes.stem': '一起做',
    'home.featuredRecipes.description': '用Cmart货架上的食材就能做的菜。',
    'home.featuredRecipes.viewAll': '查看全部食谱',
    'home.featuredRecipes.loading': '正在加载食谱...',
    'home.featuredRecipes.emptyTitle': '食谱即将上线。',
    'home.featuredRecipes.emptyDesc': '我们正在准备可用Cmart食材烹饪的菜谱。',
    'home.exploreMore.title': '继续逛逛。',
    'home.exploreMore.description': '故事、门店、留言，或来一局小游戏。',
    'home.exploreMore.about': '我们的故事。',
    'home.exploreMore.aboutDesc': '自2013年扎根雷丁。品质、社区、宾至如归。',
    'home.exploreMore.recipes': '食谱',
    'home.exploreMore.recipesDesc': '发现正宗亚洲食谱和烹饪灵感',
    'home.exploreMore.findUs': '找到我们。',
    'home.exploreMore.findUsDesc': 'ASDA购物中心，Lower Earley。巴士或开车都方便。',
    'home.exploreMore.contact': '打个招呼。',
    'home.exploreMore.contactDesc': '关于门店、商品或到访的问题。',
    'home.exploreMore.learnMore': '阅读更多',
    'home.exploreMore.viewRecipes': '查看食谱',
    'home.exploreMore.getDirections': '打开地图',
    'home.exploreMore.sendMessage': '给我们留言',
    'home.exploreMore.games': '玩一玩。',
    'home.exploreMore.gamesDesc': '限时拼出一道菜，试试我们的厨房小游戏。',
    'home.exploreMore.playNow': '开始游戏',
    
    // Footer
    'footer.description': '您在Earley, Reading值得信赖的正宗东方杂货来源。优质产品，卓越服务。',
    'footer.quickLinks': '快速链接',
    'footer.storeInfo': '商店信息',
    'footer.openingHours': '营业时间',
    'footer.privacy': '隐私政策',
    'footer.terms': '使用条款',
    
    // Recipes
    'recipes.hero.badge': '食谱',
    'recipes.hero.title': '和我们一起下厨。',
    'recipes.hero.stem': '一起做',
    'recipes.hero.description': '用Cmart货架上的食材，做出正宗亚洲味道。',
    'recipes.cycle.1': '货架上的食材。',
    'recipes.cycle.2': '饺子之夜。',
    'recipes.cycle.3': '剩米饭。',
    'recipes.cycle.4': '一桌热闹。',
    'recipes.cycle.5': 'Earley 的夜晚。',
    'recipes.filters.search': '搜索食谱...',
    'recipes.filters.cuisine': '菜系',
    'recipes.filters.difficulty': '难度',
    'recipes.filters.allergies': '排除过敏原',
    'recipes.filters.clear': '清除',
    'recipes.filters.clearAll': '清除筛选',
    'recipes.results.found': '个食谱',
    'recipes.results.foundPlural': '个食谱',
    'recipes.empty.title': '暂无结果。',
    'recipes.empty.description': '试试其他菜系、难度或搜索词。',
    'recipes.card.viewRecipe': '查看食谱',
    'recipes.categories.all': '全部',
    'recipes.categories.chinese': '中式',
    'recipes.categories.japanese': '日式',
    'recipes.categories.korean': '韩式',
    'recipes.categories.thai': '泰式',
    'recipes.categories.vietnamese': '越式',
    'recipes.categories.indian': '印式',
    'recipes.difficulty.all': '全部',
    'recipes.difficulty.easy': '简单',
    'recipes.difficulty.medium': '中等',
    'recipes.difficulty.hard': '困难',
    'recipes.filters.title': '筛选',
    'recipes.filters.searchLabel': '搜索',
    'recipes.allergies.gluten': '麸质',
    'recipes.allergies.dairy': '乳制品',
    'recipes.allergies.nuts': '坚果',
    'recipes.allergies.shellfish': '贝类',
    'recipes.allergies.eggs': '鸡蛋',
    'recipes.allergies.soy': '大豆',
    'recipes.allergies.fish': '鱼类',
    
    // Location
    'location.hero.title': '找到我们。',
    'location.hero.description': 'ASDA购物中心，Lower Earley，巴士或开车都方便，现场免费停车。',
    'location.address.title': '地址',
    'location.hours.title': '营业时间',
    'location.hours.description': '我们整周营业，方便您的购物',
    'location.bus.title': '乘巴士',
    'location.bus.routes': '巴士路线',
    'location.bus.walking': '步行距离',
    'location.bus.stop': '巴士站位于ASDA购物中心入口附近',
    'location.car.title': '开车',
    'location.car.parking': '停车',
    'location.car.location': '位置',
    'location.car.access': '从主要道路轻松到达',
    
    // Contact
    'contact.hero.title': '打个招呼。',
    'contact.hero.description': '关于门店、商品或到访的问题，给我们留言。',
    'contact.form.title': '给我们留言',
    'contact.form.description': '我们通常在24小时内回复',
    'contact.card.visit': '访问我们',
    'contact.card.visitDesc': '来店里看看我们',
    'contact.card.hours': '营业时间',
    'contact.card.response': '快速回复',
    'contact.card.responseDesc': '我们会尽快回复您',
    'contact.email': 'cmart@fortunefoods.co.uk',
    
    // Privacy Policy
    'privacy.title': '隐私政策',
    'privacy.lastUpdated': '最后更新',
    'privacy.section1.title': '介绍',
    'privacy.section1.content': 'Cmart Oriental Ltd.（"我们"、"我们的"或"本公司"）致力于保护您的隐私。本隐私政策说明当您访问我们的网站时，我们如何收集、使用、披露和保护您的信息。',
    'privacy.section2.title': '我们收集的信息',
    'privacy.section2.content': '我们可能以多种方式收集有关您的信息。我们可能收集的信息包括：',
    'privacy.section2.item1': '个人数据，如您联系我们时的姓名和电子邮件地址',
    'privacy.section2.item2': '使用数据，如您的IP地址、浏览器类型和访问的页面',
    'privacy.section2.item3': 'Cookie和跟踪技术，以增强您的体验',
    'privacy.section2.item4': '您自愿向我们提供的任何其他信息',
    'privacy.section3.title': '我们如何使用您的信息',
    'privacy.section3.content': '我们使用收集的信息来回复您的询问、改进我们的网站，并为您提供有关我们产品和服务的相关信息。',
    'privacy.section4.title': '数据安全',
    'privacy.section4.content': '我们实施适当的技术和组织措施来保护您的个人信息。但是，通过互联网传输的任何方法都不是100%安全的。',
    'privacy.section5.title': '第三方服务',
    'privacy.section5.content': '我们的网站可能包含指向第三方网站的链接。我们不对这些外部网站的隐私做法负责。',
    'privacy.section6.title': '联系我们',
    'privacy.section6.content': '如果您对本隐私政策有任何疑问，请通过我们的联系表与我们联系。',
    'privacy.contact': '如有疑问，请访问我们的联系页面。',
    
    // Terms of Use
    'terms.title': '使用条款',
    'terms.lastUpdated': '最后更新',
    'terms.section1.title': '接受条款',
    'terms.section1.content': '通过访问和使用本网站，您接受并同意受本协议条款和规定的约束。如果您不同意这些条款，请不要使用本网站。',
    'terms.section2.title': '使用许可',
    'terms.section2.content': '允许临时下载Cmart网站上材料的一份副本，仅供个人、非商业临时查看。这是许可的授予，不是所有权的转让。',
    'terms.section3.title': '免责声明',
    'terms.section3.content': 'Cmart网站上的材料按"原样"提供。Cmart不作任何明示或暗示的保证，并特此否认和否定所有其他保证。',
    'terms.section4.title': '限制',
    'terms.section4.content': '在任何情况下，Cmart或其供应商均不对因使用或无法使用Cmart网站上的材料而产生的任何损害（包括但不限于数据或利润损失）承担责任。',
    'terms.section5.title': '材料的准确性',
    'terms.section5.content': '出现在Cmart网站上的材料可能包括技术、排版或摄影错误。Cmart不保证其网站上的任何材料都是准确、完整或最新的。',
    'terms.section6.title': '链接',
    'terms.section6.content': 'Cmart尚未审查链接到其网站的所有网站，不对任何此类链接网站的内容负责。包含任何链接并不意味着Cmart的认可。',
    'terms.section7.title': '修改',
    'terms.section7.content': 'Cmart可随时修改其网站的服务条款，恕不另行通知。通过使用本网站，您同意受这些服务条款的当前版本约束。',
    'terms.section8.title': '食谱免责声明',
    'terms.section8.content': '本网站提供的食谱仅供信息和娱乐目的。Cmart Oriental Ltd. 不对任何食谱的准确性、完整性或适用性作任何陈述或保证。您承认烹饪涉及固有风险，包括但不限于食物过敏、食源性疾病和厨房事故。通过使用本网站的任何食谱，您同意 Cmart Oriental Ltd. 及其关联公司、员工和代理不对因准备、消费或使用任何食谱而产生的任何伤害、损害、损失或健康问题承担责任。您全权负责确保食材安全可食用，遵循适当的食品安全做法，并了解任何过敏或饮食限制。如果您对食物过敏、饮食要求或健康状况有疑虑，请务必咨询合格的医疗专业人员或营养师。',
    'terms.contact': '如有关于这些使用条款的问题，请通过我们的联系页面与我们联系。',
    
    // About
    'about.hero.title': '我们的故事。',
    'about.hero.badge': '我们的故事',
    'about.hero.description': '自2013年起扎根雷丁。一家注重品质与社区、让人感到宾至如归的亚洲杂货店。',
    'about.eyebrow': '自2013年',
    'about.quote.label': '我们为何开业',
    'about.quote.line1': '不只是一家店。',
    'about.quote.line2': '一个能一起分享亚洲美食、感到受欢迎的地方。',
    'about.quote.support': '这个想法仍塑造着我们的货架，以及我们对每一位顾客的接待。',
    'about.section.roots': '从雷丁走向更远。',
    'about.section.home': '有归属感的过道。',
    'about.content.paragraph1': 'Cmart于2013年在雷丁市中心起步，想法很简单：不只是一家店，而是人们可以一起分享亚洲美食、感到受欢迎的地方。在顾客的支持与团队的坚持下，我们一路成长到今天。',
    'about.content.paragraph2': '业务扩展到雷丁以外，品质与社区仍是核心。货架上的每件商品都经过精心挑选。我们直接从远东供应商采购，让您买到新鲜、正宗的食材。',
    'about.content.paragraph3': '我们的过道里有杂货，也有故事与归属感。无论您是常客还是第一次光临，您都是Cmart大家庭的一员。',
    'about.content.paragraph4': '我们仍坚持创立时的承诺：优质商品、温暖接待，用心服务每一位顾客。',
    'about.content.thanks': '感谢您与我们同行。',
    'about.storeInfo.title': '商店信息',
    'about.storeInfo.address': '地址',
    'about.storeInfo.hours': '营业时间',
    'about.storeInfo.parking': '停车',
    'about.storeInfo.parkingDesc': '附近有便利的停车位',
    'about.cta.findUs': '找到我们',
    'about.cta.sayHello': '打个招呼',
    'about.cta.cook': '一起下厨',
    
    // Games
    'games.back': '返回首页',
    'games.score': '分数',
    'games.time': '时间',
    'games.streak': '连击',
    'games.highScore': '最高分',
    'games.start': '开始游戏',
    'games.playAgain': '再玩一次',
    'games.gameOver': '游戏结束！',
    'games.points': '分',
    'games.correct': '正确',
    'games.wrong': '错误',
    'games.newHighScore': '新最高分！',
    'games.recipeBuilder.title': '食谱构建挑战',
    'games.recipeBuilder.description': '匹配食材到食谱并得分！',
    'games.recipeBuilder.instructions': '游戏说明',
    'games.recipeBuilder.rule1': '为每个食谱选择正确的食材',
    'games.recipeBuilder.rule2': '每个正确食材获得+10分',
    'games.recipeBuilder.rule3': '每连续3个正确获得+20奖励（连击）',
    'games.recipeBuilder.rule4': '完美完成食谱获得+50奖励',
    'games.recipeBuilder.selectIngredients': '选择正确的食材：',
    'games.recipeBuilder.availableIngredients': '可用食材',
    
    // Location - additional keys
    'location.hero.badge': '路线',
    'location.map.title': '地图',
    'location.map.openMaps': '在 Google 地图中打开',
    'location.address.description': '位于ASDA购物中心内，停车购物都方便。',
    'location.transport.title': '怎么来。',
    'location.transport.description': '巴士或开车，下车后步行一小段就到。',
    'location.bus.routesLabel': '线路',
    'location.bus.stopDesc': '在Lower Earley站下车',
    'location.bus.walkingLabel': '步行',
    'location.bus.walkingTime': '2-3分钟',
    'location.car.parkingLabel': '停车',
    'location.car.parkingDesc': 'ASDA停车场为顾客提供免费停车。',
    'location.car.locationLabel': '位置',
    'location.car.locationDesc': '商店位于ASDA购物中心内',
    'location.days.monThu': '周一至周四',
    'location.days.friday': '周五',
    'location.days.saturday': '周六',
    'location.days.sunday': '周日',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

